import { useState } from "react";
import { api } from "../lib/api";
import type { Issue } from "../types";
import type { Insight } from "../lib/gemini";

const TAG_META: Record<Insight["tag"], { icon: string; label: string }> = {
  hotspot: { icon: "📍", label: "Hotspot" },
  trend: { icon: "📈", label: "Trend" },
  seasonal: { icon: "🌧️", label: "Seasonal" },
  risk: { icon: "⚠️", label: "Risk" },
  info: { icon: "💡", label: "Insight" },
};

// AI-powered forward-looking analysis over a set of issues.
export function PredictiveInsights({ issues }: { issues: Issue[] }) {
  const [insights, setInsights] = useState<Insight[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [aiPowered, setAiPowered] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function run() {
    setLoading(true);
    setError(null);
    try {
      const res = await api.getPredictiveInsights(issues);
      setInsights(res.insights);
      setAiPowered(res.aiPowered);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Couldn't generate insights");
    } finally {
      setLoading(false);
    }
  }

  if (issues.length === 0) return null; // nothing to forecast yet

  return (
    <section className="insights card">
      <div className="insights-head">
        <h2>🔮 Predictive Insights</h2>
        <button className="btn btn-primary btn-sm" disabled={loading} onClick={() => void run()}>
          {loading ? "Analysing…" : insights ? "↻ Refresh" : "✨ Generate"}
        </button>
      </div>
      <p className="muted small">
        AI forecasts emerging hotspots, trends and seasonal risks from current reports — with a
        recommended action for each.
      </p>

      {error && <div className="error-box">{error}</div>}
      {!insights && !loading && (
        <p className="muted">Tap Generate to see what the AI predicts for this area.</p>
      )}

      {insights && (
        <>
          <div className="insights-grid">
            {insights.map((it, i) => {
              const meta = TAG_META[it.tag] ?? TAG_META.info;
              return (
                <div key={i} className={`insight-card ${it.tag}`}>
                  <span className="insight-tag">
                    {meta.icon} {meta.label}
                  </span>
                  <strong>{it.title}</strong>
                  <p className="muted small">{it.detail}</p>
                  <p className="insight-action">→ {it.action}</p>
                </div>
              );
            })}
          </div>
          <p className="insights-credit">
            {aiPowered ? "✨ Generated by Google Gemini" : "Heuristic summary (AI unavailable)"}
          </p>
        </>
      )}
    </section>
  );
}
